
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.103.92.234:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 47.103.92.234
      port: 27017
      database: aop-demo
      repositories:
        enabled: true
server:
  port: 9999